project:
  type: website
    
website:
  site-url: https://archmetaldbm.github.io/globalid
  repo-url: https://github.com/archmetalDBM/GlobaLID
  favicon: favicon.png
  title: "![Logo GlobaLID](/assets/globalid-logo.svg){height=60px} GlobaLID"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
    right: 
      - about.qmd

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    #linkcolor: "#007bff"
    toc: true
    toc-location: left

execute:
  freeze: auto
  